<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <RootNamespace>Elsie.Sample.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Elsie" Version="0.3.0-beta.2" />
    <PackageReference Include="Elsie.Validation" Version="0.3.0-beta.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
  </ItemGroup>
</Project>
