<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>In-memory and socket test hosts for Elsie.</Description>
    <RootNamespace>Elsie.Testing</RootNamespace>
    <AssemblyName>Elsie.Testing</AssemblyName>
    <PackageId>Elsie.Testing</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Elsie.Core\Elsie.Core.csproj" />
    <ProjectReference Include="..\Elsie\Elsie.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>
