<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Elsie.Auth\Elsie.Auth.csproj" />
    <ProjectReference Include="..\..\src\Elsie.Extensions.Auth.Redis\Elsie.Extensions.Auth.Redis.csproj" />
    <PackageReference Include="Testcontainers" />
  </ItemGroup>
</Project>
