<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Elsie.Web\Elsie.Web.csproj" />
    <ProjectReference Include="..\..\src\Elsie.Testing\Elsie.Testing.csproj" />
    <ProjectReference Include="..\..\src\Elsie.Auth\Elsie.Auth.csproj" />
  </ItemGroup>
</Project>
