<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Elsie\Elsie.csproj" />
    <ProjectReference Include="..\..\src\Elsie.Auth\Elsie.Auth.csproj" />
    <ProjectReference Include="..\..\src\Elsie.Cors\Elsie.Cors.csproj" />
    <ProjectReference Include="..\..\src\Elsie.Validation\Elsie.Validation.csproj" />
    <ProjectReference Include="..\..\src\Elsie.Views\Elsie.Views.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" VersionOverride="8.0.1" />
  </ItemGroup>
</Project>
